//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Langs {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Training.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руки.
        /// </summary>
        public static string arm_lan {
            get {
                return ResourceManager.GetString("arm_lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Календарь.
        /// </summary>
        public static string cal_lan {
            get {
                return ResourceManager.GetString("cal_lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +В.Тела.
        /// </summary>
        public static string ch_cm_lan1 {
            get {
                return ResourceManager.GetString("ch_cm_lan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +Н.Тела.
        /// </summary>
        public static string ch_cm_lan2 {
            get {
                return ResourceManager.GetString("ch_cm_lan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +Руки.
        /// </summary>
        public static string ch_cm_lan3 {
            get {
                return ResourceManager.GetString("ch_cm_lan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +ФИО.
        /// </summary>
        public static string ch_cm_lan4 {
            get {
                return ResourceManager.GetString("ch_cm_lan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реверс.
        /// </summary>
        public static string ch_cm_lan5 {
            get {
                return ResourceManager.GetString("ch_cm_lan5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейтинг.
        /// </summary>
        public static string ch_lan {
            get {
                return ResourceManager.GetString("ch_lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить запись.
        /// </summary>
        public static string dt_cm_lan1 {
            get {
                return ResourceManager.GetString("dt_cm_lan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывести.
        /// </summary>
        public static string dt_cm_lan2 {
            get {
                return ResourceManager.GetString("dt_cm_lan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить файл.
        /// </summary>
        public static string dt_cm_lan3 {
            get {
                return ResourceManager.GetString("dt_cm_lan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить экран.
        /// </summary>
        public static string dt_cm_lan4 {
            get {
                return ResourceManager.GetString("dt_cm_lan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дневник Тренировок.
        /// </summary>
        public static string dt_lan {
            get {
                return ResourceManager.GetString("dt_lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Низ тела.
        /// </summary>
        public static string lowbody_lan {
            get {
                return ResourceManager.GetString("lowbody_lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тренировка.
        /// </summary>
        public static string tr_lan {
            get {
                return ResourceManager.GetString("tr_lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верх тела.
        /// </summary>
        public static string upbody_lan {
            get {
                return ResourceManager.GetString("upbody_lan", resourceCulture);
            }
        }
    }
}
